### ISSUE TITLE
CurseForge publication

### ISSUE THREAD

**Issue by FChapeau** [yor42/Solar-Apocalypse-Reforged#2]
I'm trying to build a Curse modpack that would include this mod, but it not being on Curse, I have to jump through a lot of hoops to make it work, whereas it would be easy-peasy to include it in the pack if it were on Curse.

Would it cause issues with SmushyTaco?

**Comment by yor42** [comment]
Hi. I'm sorry for late reply.
There should be no problem with license for me since Solar apocalypse Refabricated is LGPL-3.0.
however for now i don't have plan to publish this mod on curseforge.
Its not like I hate CF or anything, but I just want to stay off from public since I'm likely to be unable to catch up public Modded MC player's quality expectation in terms of bugfix and update.
(I'm college student with little programming knowledge unlike other dev with lot of knowledge on java.)
but I'll do consider as an option.

**Comment by FChapeau** [comment]
I understand, and since I'm going through the approval process on CF myself for my modpack, I understand why you'd want to stay away from it for now.

I can work around it, it's mostly for convenience and workflow, it's far from critical, but would be greatly appreciated.

Also, from one software engineer to another, good luck with college!

**Comment by yor42** [comment]
Thank you. since there's demand for curseforge now I'll think about it again.
If you don't mind I will leave this open for now until i firmly decide what to do.
